# Generated by Django 5.0.3 on 2024-04-12 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_coupon_account_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
