# Generated by Django 5.0.3 on 2024-04-01 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_categoryoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='id',
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='category.category'),
        ),
    ]
