# Generated by Django 5.0.3 on 2024-04-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_categoryoffer_id_alter_categoryoffer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
