# Generated by Django 5.0.3 on 2024-04-06 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_categoryoffer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='category.category'),
        ),
    ]
