# Generated by Django 5.0.3 on 2024-04-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_categoryoffer_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryOffer',
        ),
    ]
