# Generated by Django 5.0.3 on 2024-04-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
