# Generated by Django 5.0.3 on 2024-04-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scarts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
