# Generated by Django 5.0.3 on 2024-04-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productoffer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='offer_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
