# Generated by Django 5.0.3 on 2024-04-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_productoffer_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
