# Generated by Django 5.0.3 on 2024-04-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_productattribute_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(upload_to='product'),
        ),
    ]
