# Generated by Django 5.0.3 on 2024-04-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_productattribute_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
