# Generated by Django 5.0.3 on 2024-04-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productoffer_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='created_date',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
