# Generated by Django 5.0.3 on 2024-04-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=255),
        ),
    ]
