# Generated by Django 5.0.3 on 2024-04-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
