# Generated by Django 5.0.3 on 2024-04-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_wallettransaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_price',
            field=models.PositiveIntegerField(),
        ),
    ]
