# Generated by Django 5.0.3 on 2024-04-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_payment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
