# Generated by Django 5.0.3 on 2024-04-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_coupon_order_cancellation_reason_order_return_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
