# Generated by Django 5.0.3 on 2024-04-14 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_usercoupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
