# Generated by Django 5.0.3 on 2024-04-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('', ''), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], max_length=100),
        ),
    ]
